#Descarga de datos

Ejemplos de descarga de datos para generar un DataFrame.

Inicialmente se carga la librería [pandas](https://pandas.pydata.org/) para leer y manipular los datos

In [1]:
import pandas as pd

## Descarga básica de un archivo csv

Se van a leer los datos del archivo [ETH.csv](https://github.com/nicoavilan/Bases-de-datos/blob/main/ETH.csv) para hacerlo se toma la dirección de los datos crudos (raw) [ETH.csv (datos crudos)](https://raw.githubusercontent.com/nicoavilan/Bases-de-datos/main/ETH.csv)

In [2]:
url = "https://raw.githubusercontent.com/nicoavilan/Bases-de-datos/main/ETH.csv"
df = pd.read_csv(url)
df

,Unnamed: 0,Date,Symbol,Open,High,Low,Close,Volume
0,0,2020-03-13 08-PM,ETHUSD,129.94,131.82,126.87,128.71,1940673.93
1,1,2020-03-13 07-PM,ETHUSD,119.51,132.02,117.10,129.94,7579741.09
2,2,2020-03-13 06-PM,ETHUSD,124.47,124.85,115.50,119.51,4898735.81
3,3,2020-03-13 05-PM,ETHUSD,124.08,127.42,121.63,124.47,2753450.92
4,4,2020-03-13 04-PM,ETHUSD,124.85,129.51,120.17,124.08,4461424.71
...,...,...,...,...,...,...,...,...
23669,23669,2017-07-01 03-PM,ETHUSD,265.74,272.74,265.00,272.57,1500282.55
23670,23670,2017-07-01 02-PM,ETHUSD,268.79,269.90,265.00,265.74,1702536.85
23671,23671,2017-07-01 01-PM,ETHUSD,274.83,274.93,265.00,268.79,3010787.99
23672,23672,2017-07-01 12-PM,ETHUSD,275.01,275.01,271.00,274.83,824362.87
23673,23673,2017-07-01 11-AM,ETHUSD,279.98,279.99,272.10,275.01,679358.87