<a href="https://colab.research.google.com/github/nicoavilan/Descarga-de-datos/blob/main/Descarga_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Descarga de datos

Ejemplos de descarga de datos para generar un DataFrame.

Inicialmente se carga la librería [pandas](https://pandas.pydata.org/) para leer y manipular los datos

In [ ]:
import pandas as pd

## Descarga básica de un archivo csv

Se van a leer los datos del archivo [ETH.csv](https://github.com/nicoavilan/Bases-de-datos/blob/main/ETH.csv) para hacerlo se toma la dirección de los datos crudos (raw) [ETH.csv (datos crudos)](https://raw.githubusercontent.com/nicoavilan/Bases-de-datos/main/ETH.csv)

In [ ]:
url = "https://raw.githubusercontent.com/nicoavilan/Bases-de-datos/main/ETH.csv"
df = pd.read_csv(url)
df

,Unnamed: 0,Date,Symbol,Open,High,Low,Close,Volume
0,0,2020-03-13 08-PM,ETHUSD,129.94,131.82,126.87,128.71,1940673.93
1,1,2020-03-13 07-PM,ETHUSD,119.51,132.02,117.10,129.94,7579741.09
2,2,2020-03-13 06-PM,ETHUSD,124.47,124.85,115.50,119.51,4898735.81
3,3,2020-03-13 05-PM,ETHUSD,124.08,127.42,121.63,124.47,2753450.92
4,4,2020-03-13 04-PM,ETHUSD,124.85,129.51,120.17,124.08,4461424.71
...,...,...,...,...,...,...,...,...
23669,23669,2017-07-01 03-PM,ETHUSD,265.74,272.74,265.00,272.57,1500282.55
23670,23670,2017-07-01 02-PM,ETHUSD,268.79,269.90,265.00,265.74,1702536.85
23671,23671,2017-07-01 01-PM,ETHUSD,274.83,274.93,265.00,268.79,3010787.99
23672,23672,2017-07-01 12-PM,ETHUSD,275.01,275.01,271.00,274.83,824362.87
23673,23673,2017-07-01 11-AM,ETHUSD,279.98,279.99,272.10,275.01,679358.87

## Descarga de un archivo csv con caracteres latinos (ñ, á, é, í, ó, ú, etc)

Se van a leer los datos del archivo [OSB_EnfTransm-COVID-19 April 2020.csv](https://github.com/nicoavilan/Bases-de-datos/blob/main/OSB_EnfTransm-COVID-19%20April%202020.csv) para hacerlo se toma la dirección de los datos crudos (raw) [OSB_EnfTransm-COVID-19 April 2020.csv (datos crudos)](https://raw.githubusercontent.com/nicoavilan/Bases-de-datos/main/OSB_EnfTransm-COVID-19%20April%202020.csv)

Si los datos están separados con ; (punto y coma) se debe especificar en la lectura de los datos usando la instrucción `sep= ";"`.

In [ ]:
url = "https://raw.githubusercontent.com/nicoavilan/Bases-de-datos/main/OSB_EnfTransm-COVID-19%20April%202020.csv"
df1 = pd.read_csv(url,encoding = "latin-1", sep= ";" )
df1

,ID de caso,Fecha de diagnóstico,Ciudad de residencia,Localidad de residencia,Edad,Sexo,Tipo de caso,Ubicación,Estado
0,1.0,6/03/2020,Bogotá,01 - Usaquén,19.0,F,Importado,Casa,Recuperado
1,2.0,10/03/2020,Bogotá,10 - Engativá,22.0,F,Importado,Casa,Recuperado
2,3.0,10/03/2020,Bogotá,10 - Engativá,28.0,F,Importado,Casa,Recuperado
3,4.0,12/03/2020,Bogotá,09 - Fontibón,36.0,F,Importado,Casa,Recuperado
4,5.0,12/03/2020,Bogotá,08 - Kennedy,42.0,F,Importado,Casa,Recuperado
...,...,...,...,...,...,...,...,...,...
2535,2536.0,28/04/2020,Bogotá,05 - Usme,34.0,F,En Estudio,Hospital,Severo
2536,2537.0,28/04/2020,Bogotá,05 - Usme,39.0,M,En Estudio,Hospital,Severo
2537,2538.0,28/04/2020,Bogotá,05 - Usme,28.0,F,En Estudio,Casa,Moderado
2538,2539.0,28/04/2020,Bogotá,05 - Usme,69.0,M,En Estudio,Hospital,Severo
2539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN